[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
hex = "0.4.3"
openssl = "0.10.62"
itertools = "0.12.0"
rand = "0.8.5"
xor = { path = "./xor" }
