[package]
name = "xor_cipher"
version = "0.1.0"
authors = ["Chris Dickerman <chrisdickerman.main@gmail.com>"]
edition = "2021"

[dependencies]
xor = { path = "../xor"}
itertools = "0.12.0"
hex = "0.4.3"
base64 = "0.21.5"