[package]
name = "aes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.62"
base64 = "0.21.5"
xor_cipher ={ path = "../xor_cipher" }
xor ={ path = "../xor" }